### ISSUE TITLE
Moving interface between vdoms

### ISSUE THREAD

**Issue by patrickpreuss** [spotify/pyfg#8]
Hi 
Tried to move Interfaces from vdom to another, when static router still on the Interface, no all nessessay steps are build.

**Comment by StefanLindblom** [comment]
Hi there @patrickpreuss !
I'm very sorry for the extreme delay in getting back to you...
Is this still an issue for you?
Since FortiOS will present the vdom field in multiple places for a given interface, it can be a bit tricky. For example you will see the same interface from both `config global / show system interface` and `config vdom / edit myvdom / show system interface`.

/Stefan Lindblom

**Comment by StefanLindblom** [comment]
Hi again, closing this issue for now.
